### ISSUE TITLE
Buildings being identified as overlapping that are actually bad geometry

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#108]
Currently Underpass is incorrectly marking some bad geometry buildings as overlapping.

**Comment by emi420** [comment]
On the last replicator run, there are no `overlaping` on the validation results:

<img width="226" alt="Screen Shot 2022-09-26 at 10 22 38" src="https://user-images.githubusercontent.com/1226194/192287993-f188fb9b-f066-4503-bf9c-7570d4721f49.png">

Also, tests seems to be working ok.

Maybe this issue is already fixed?

**Comment by emi420** [comment]
Latest changes included fixes and tests for overlapping and bad geometry, we can close this issue.
