### ISSUE TITLE
Data quality dumps for individual user is empty

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/underpass#205]
While downloading the CSV/JSON dumps of data quality reports for each user from Mapathon detailed page and user-reports page, all dumps are empty. I am unable to decide it is because the user's data creation is high quality or if the validation table is missing to capture data.

cc @emi420 @robsavoye

**Comment by itskshitiz321** [comment]
![image](https://user-images.githubusercontent.com/36752999/171111733-e3ca4ed3-ca21-4d23-a02e-1ac881a05c58.png)
Major cause for this bug is underpass doesn't have created_at and hashtags information populated on lot of rows , when intersected with validation table ~ One enhancement on API is also needed i.e. adding "all" on supported dataquality related endpoint

**Comment by itskshitiz321** [comment]
cc : @ramyaragupathy
