### ISSUE TITLE
Gzip and request errors can cause the replication process to stop working

### ISSUE THREAD

**Issue by emi420** [hotosm/underpass#314]

**Comment by emi420** [comment]
If you see this path:

https://planet.openstreetmap.org/replication/changesets/003/115/

File numbers stops at 723 instead of 999, this is causing an issue with the replicator. There's an easy fix for this one.

The other issue is happening with Gzip files, sometimes the file is corrupted and the replicator stops incrementing the path.

**Comment by mmd-osm** [comment]
You know about this, right?

> Under no circumstances should you attempt to just fetch diffs by incrementing the sequence number as incomplete diffs may be present beyond the one identified in the state file.

https://wiki.openstreetmap.org/wiki/Planet.osm/diffs

**Comment by emi420** [comment]
Hey, thank you for contributing @mmd-osm . Yes, but Underpass uses a multi-threading process in which it tries to get a batch of files, incrementing the path. If something goes wrong it needs to check the timestamp of the last processed change to see if there was a request issue or if it reached current time.

So, to fix this issue:

* If the response status is 404, like in this case, Underpass will skip the file to prevent the replication process to stuck there, and save the path into the log file so we can process it later.

* If there’s a connection problem, it will keep trying until the request is successful.

**Comment by mmd-osm** [comment]
We’ve just realized that changeset diffs may have some gaps due to bugs in the extraction logic. As a consequence this means the files you’re consuming may be incomplete.

The best bet to backfill older changesets is to use a dump instead: https://planet.openstreetmap.org/planet/changesets-latest.osm.bz2 then continue with changeset diffs.

Issues with changeset diffs keep on happening from time to time…
