### ISSUE TITLE
Can't write to osm2pgsql database

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#57]
After merging the pull request, I tried it running with these options:
./replicator --osm2pgsqlserver localhost/osm2pgsql -v -d -l -f hour -u 000/068/372 -m

What I get is this error:
[893212:2] 14056 ERROR: Couldn't upsert node/points record: ERROR:  relation "osm2pgsql_pgsql.planet_osm_nodes" does not exist
LINE 2:       INSERT INTO osm2pgsql_pgsql.planet_osm_nodes

You can see that planet_osm_nodes is not part of the default, I assume it's only created when doing an update. This was updating a database imported using osm2pgsql.

osm2pgsql=# \dt
              List of relations
 Schema |        Name        | Type  | Owner 
--------+--------------------+-------+-------
 public | planet_osm_line    | table | rob
 public | planet_osm_point   | table | rob
 public | planet_osm_polygon | table | rob
 public | planet_osm_roads   | table | rob
 public | spatial_ref_sys    | table | rob
(5 rows)

**Comment by elpaso** [comment]
The functionality was developed and tested with osm2pgsql 1.5.1, an import and execution test is up and running on CI https://github.com/hotosm/underpass/runs/3761813283?check_suite_focus=true#step:9:4

osm2pgsql is a complex application and in order to get the "middle" tables support [1] you might need to do the initial import with the correct command line, see the README here : https://github.com/hotosm/underpass/tree/master/testsuite/testdata

We can move that information to another location, just tell me where you think it fits.

To check if you have the correct schema, you can have a look to the osm2pgsql schema used in the test (it was generated with the same command line that it is written in the README).

https://osm2pgsql.org/doc/manual.html#middle

**Comment by robsavoye** [comment]
I did use the correct options when importing. What I noticed is the additional tables get created, but when the import is done, they get dropped. I'd like to see an sql file to create the schema with all the tables. There are other schemas in the /data directory that Undepass uses when it's setup so everything works out of the box, without requiring a a user to read the documentation.

**Comment by elpaso** [comment]
> I did use the correct options when importing. What I noticed is the additional tables get created, but when the import is done, they get dropped. I'd like to see an sql file to create the schema with all the tables.

Which is exactly `https://github.com/hotosm/underpass/blob/master/testsuite/testdata/pgsql_test_schema.sql`, do you want it moved to the data folder?

**Comment by robsavoye** [comment]
I think I'd leave that file where it is, but I didn't notice that buried in the test data. By yes, a copy in /data would be good, except it needs to use the public namespace instead of osm2pgsql_pgsql.

**Comment by robsavoye** [comment]
I get a bunch of these errors after merging the latest patch:
[1715464:2] 553323 ERROR: Couldn't upsert way/road record: ERROR:  lwpoly_from_lwlines: shell must be 
closed
