### ISSUE TITLE
BUG: Different stats for added and modified fields in changeset table

### ISSUE THREAD

**Issue by omranlm** [hotosm/underpass#73]
After the recent underpass enhancements and fixes and since it has been running continuously for almost weeks, validating some added modified stats on the changeset level.
For changeset ID [107235440](https://www.openstreetmap.org/api/0.6/changeset/107235440/download), which underpass has scanned on 3 Nov, underpass calculated 7 added highways and no modified highways.
While checking the changeset on [OSM](https://www.openstreetmap.org/api/0.6/changeset/107235440/download), there are 8 added and 8 modified highways!
The parsing of osm change file might be the issue 
![image](https://user-images.githubusercontent.com/39491329/140757107-d3b4efd7-eaf9-4f4d-b66f-365df1394afe.png)

Another invalid changeset is ID = [104497858 ](https://www.openstreetmap.org/api/0.6/changeset/104497858/download)
Which shows (as below) 3 added school and 3 added building while the changeset ID [104497858 ](https://www.openstreetmap.org/api/0.6/changeset/104497858/download) doesn't have ant new added schools but has 3 modified ones and no building tag!

![image](https://user-images.githubusercontent.com/39491329/140759095-8d2a4727-89a9-4cec-a654-1a44db3e11da.png)

@robsavoye

**Comment by robsavoye** [comment]
Part of the problem is determining if the feature is in a priority country or not. After comparing the list of countries covered by audacious funding with what's in the geoboundaries table, some countries are missing. Underpass uses a "priority.geojson" file which was created using the geoboundaries table, so some features are determined to not be in a priority country, when they actually are.
To fix this problem, the geoboundaries tables needs to be improved, and the priority.geojson file regenerated.

**Comment by itskshitiz321** [comment]
**Update on the issue :** Feature is in priority country boundary used by underpass located in data/prority.geojson , which means its not about the boundary , fixing geo boundaries table may not solve this issue.
Here Black Rectangle is Changeset 104497858  , Redline is our Priority Countries 
![image](https://user-images.githubusercontent.com/36752999/144021775-d1c0585f-3d25-4821-a88a-597feecb3008.png)
 
![image](https://user-images.githubusercontent.com/36752999/144021832-05b90a4a-8643-4db1-850c-42cc05b54e7f.png)
****
