### ISSUE TITLE
overlaps function in validate.hh does not consider layer value

### ISSUE THREAD

**Issue by jwalseth-tableau** [hotosm/underpass#93]
It's allowed for buildings to overlap if they have differing depths. Like, if one of the buildings has layer=1 or layer=-1. This is just something I noticed while looking around at the code. Cheers.

**Comment by robsavoye** [comment]
OSM doesn't really have layers, it's all one big layer. Only editors support layers. But yes, the current version of the code (in a branch still) does conflation for overlapping and duplicate buildings between multiple datasets, so would be able to handle conflating between layers. Thanks for looking at the code!

**Comment by robsavoye** [comment]
Since I happened to be looking at this code again today, I'll mention there will be two overlap functions. The one in validate.hh is focused on overlapping buildings within a single osmchange file. I'm currently developing a additional one that does overlapping and duplicate buildings using an osm database for conflation. That will obviously be more focused on mapathons due to issues with SQL performance with large datasets by creating a view using the project boundary.

**Comment by mmd-osm** [comment]
I believe OP wanted to raise your awareness for the https://wiki.openstreetmap.org/wiki/Key:layer tag, and the respective special logic you need to implement in this case to get meaningful results in the presence of this tag.

**Comment by robsavoye** [comment]
Thanks for the pointer to key:layer, very interesting. I'd need to find some examples to see how it would effect the osmchange file. I'd assume (usually a bad idea), I could just loop through the layers and do the same processing.

**Comment by robsavoye** [comment]
I found some examples of where **layer** is set for buildings on a hillside, which also overlap a little, so I'll add this to the test case. If **layer>1**, underpass will ignore overlapping buildings.

**Comment by robsavoye** [comment]
Works as of #a2047cd, it's in master now. Turned out to be much easier to implement once I made a good test case with the example I found. Thanks for pointing out the issue with the layer tag!
