### ISSUE TITLE
Underpass does not always start with the right file

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#99]
Replicator sometimes starts with the right file to download from the replication server, but not always.If the change files are cached on disk, it seems to work better, but not always. Also the -u option appears not to work always either. Replicator must start reliably with a timestamp, regardless of whether any files have been cached.

**Comment by robsavoye** [comment]
The test case for the fetch* functions to get the starting remote file path is broken, and needs to be refactored. For some reason the CI support missed the test  case core dumping.

**Comment by ramyaragupathy** [comment]
@robsavoye - is it already available on the Underpass EC2 machine?

**Comment by emi420** [comment]
This seems to be caused by a bug with `PlanetReplicator::findRemotePath`.

Running the test program `planetreplicator-test` with the `timestamp` option will result in a PASSED test for timestamps after 2016-07-08T23:31 included:

```
./testsuite/libunderpass.all/planetreplicator-test -t 2016-07-08T23:31
...
Filespec: replication/minute/002/000/903.osc.gz
Destdir: replication/minute/002/000
PASSED: Find remote path from timestamp +/- 1 day (2016-Jul-08 23:31:00) (2016-Jul-09 12:56:57)
```
But the test will FAIL before that timstamp, resulting in a _Segmentation fault_ error:

```
./testsuite/libunderpass.all/planetreplicator-test -t 2016-07-08T23:30
...
Filespec: replication/minute/002/-01/096.osc.gz
Destdir: replication/minute/002/-01
no read access: iostream error
Segmentation fault
```
 
Tests for any timestamp before `2016-07-08T23:30` seems to be failing, but passing after that (including very recent ones).

**Comment by robsavoye** [comment]
Any update on if Underpass is still failing with a timestamp before 2016-07-08T23:30 ?
